import { useEffect, useState } from "react";
import { Monitor, Smartphone, Tablet, X } from "lucide-react";
import { apiRequest } from "../lib/api";
import LandingPageBuilderStudio from "./LandingPageBuilderStudio";
import LandingPageRenderer, { type LandingPageDocument } from "./LandingPageRenderer";
import { createLandingPageDocument } from "./landingBuilder";

type CreatedPage = { _id: string; name: string; type: "landing" | "buy-now"; builderDocument?: LandingPageDocument; sections?: Array<{ type?: string; template?: string; formId?: string | null }> };
type LandingPageCreatedDetail = { page?: CreatedPage };
function templateKeyForPage(page: CreatedPage): Parameters<typeof createLandingPageDocument>[0] { const template = page.sections?.find((section) => section.type === "hero")?.template; const mapping: Record<string, Parameters<typeof createLandingPageDocument>[0]> = { hero: "agency", consultation: "service-business", launch: "creator-brand", local: "local-business" }; return mapping[template ?? ""] ?? "creator-brand"; }
function buildInitialDocument(page: CreatedPage): LandingPageDocument { if (page.builderDocument) return page.builderDocument; const document = createLandingPageDocument(templateKeyForPage(page)); const formId = page.sections?.find((section) => section.type === "form")?.formId; if (formId) { document.sections.push({ id: "form-1", type: "form", visible: true, blocks: [{ type: "form", formId }], settings: {} }); document.references.push({ type: "form", id: formId }); } return document; }

export default function LandingPageBuilderHost() {
  const [page, setPage] = useState<CreatedPage | null>(null); const [document, setDocument] = useState<LandingPageDocument | null>(null); const [previewDocument, setPreviewDocument] = useState<LandingPageDocument | null>(null); const [device, setDevice] = useState<"mobile" | "tablet" | "desktop">("mobile"); const [loading, setLoading] = useState(false); const [error, setError] = useState<string | null>(null);
  useEffect(() => { async function openBuilder(detail: LandingPageCreatedDetail) { if (!detail.page || detail.page.type !== "landing") return; setLoading(true); setError(null); try { const response = await apiRequest<{ page: CreatedPage }>(`/pages/${detail.page._id}`); const initialDocument = buildInitialDocument(response.page); if (!response.page.builderDocument) await apiRequest(`/pages/${response.page._id}`, { method: "PATCH", body: JSON.stringify({ builderVersion: 1, builderDocument: initialDocument }) }); setPage(response.page); setDocument(initialDocument); } catch (err) { setError(err instanceof Error ? err.message : "Unable to open the landing page editor"); } finally { setLoading(false); } } const handleCreated = (event: Event) => { void openBuilder((event as CustomEvent<LandingPageCreatedDetail>).detail); }; window.addEventListener("buynow:landing-page-created", handleCreated); return () => window.removeEventListener("buynow:landing-page-created", handleCreated); }, []);
  if (!page || !document) { if (!loading && !error) return null; return <div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/30 p-4 backdrop-blur-sm"><div className="w-full max-w-sm rounded-[24px] bg-white p-5 shadow-2xl">{loading && <div className="text-[15px] font-bold text-[#111111]">Opening your landing page editor…</div>}{error && <><div className="text-[15px] font-bold text-[#111111]">We couldn't open the editor</div><div className="mt-2 text-[13px] leading-5 text-[#6B7280]">{error}</div><button onClick={() => setError(null)} className="mt-4 rounded-xl bg-[#0325D9] px-4 py-2.5 text-[13px] font-bold text-white">Close</button></>}</div></div>; }
  const previewWidth = device === "mobile" ? "w-[390px]" : device === "tablet" ? "w-[768px] max-w-full" : "w-full max-w-[1180px]";
  return <div className="fixed inset-0 z-[100] bg-white"><LandingPageBuilderStudio pageId={page._id} initialDocument={document} onBack={() => { setPage(null); setDocument(null); setPreviewDocument(null); }} onPreview={setPreviewDocument} />{previewDocument && <div className="fixed inset-0 z-[200] flex flex-col bg-[#111111]/70 p-2 sm:p-5" role="dialog" aria-modal="true" aria-label="Landing page preview"><header className="mx-auto flex w-full max-w-[1180px] shrink-0 items-center justify-between rounded-t-2xl bg-white px-4 py-3 shadow-sm"><div><div className="text-[15px] font-black">Preview</div><div className="text-[11px] text-[#9CA3AF]">{page.name} · current edits</div></div><div className="flex items-center gap-1 rounded-xl bg-[#F7F8FC] p-1">{([['mobile', Smartphone], ['tablet', Tablet], ['desktop', Monitor]] as const).map(([key, Icon]) => <button key={key} type="button" onClick={() => setDevice(key)} className={`flex h-9 items-center gap-1.5 rounded-lg px-3 text-[11px] font-bold ${device === key ? "bg-white text-[#111111] shadow-sm" : "text-[#6B7280]"}`}><Icon size={14} />{key[0].toUpperCase() + key.slice(1)}</button>)}<button type="button" onClick={() => setPreviewDocument(null)} className="ml-1 flex h-9 w-9 items-center justify-center rounded-full bg-white" aria-label="Close preview"><X size={17} /></button></div></header><div className="min-h-0 flex-1 overflow-auto bg-[#ECEEF3] p-3 sm:p-8"><div className={`mx-auto min-h-full overflow-hidden bg-white shadow-xl transition-all ${previewWidth}`}><LandingPageRenderer document={previewDocument} interactive /></div></div><footer className="mx-auto w-full max-w-[1180px] shrink-0 rounded-b-2xl border-t border-[#EEF0F5] bg-white px-4 py-2.5 text-center text-[11px] font-semibold text-[#6B7280]">Live preview · unsaved changes included · switch devices to check responsive presentation</footer></div>}</div>;
}
